### ISSUE TITLE
The thing with the function naming ...

### ISSUE THREAD

**Issue by petermeissner** [Ironholds/rbitrary#1]
Another idea ...

Having a GNU/Linux background function names like grep and ls might seem straight forward and not noteworthy but for me switching from Windows to Linux was a big "Aha"-moment when I realized that a lot of function names were simply the same within R and within the command line.

**Comment by Ironholds** [comment]
Oooh, that's great!

**Comment by petermeissner** [comment]
- cat
- ls
- grep

**Comment by richfitz** [comment]
- rm

**Comment by zkamvar** [comment]
- cd
- pwd

... OH, WAIT

**Comment by petermeissner** [comment]
- unlink
- iconv 
- basename
- dirname 
- break
- tail
- head
- seq 
- time -> Sys.time
- sleep -> Sys.sleep

http://ss64.com/bash/
