### ISSUE TITLE
on the subject of "<-"  vs  "="

### ISSUE THREAD

**Issue by cellocgw** [Ironholds/rbitrary#14]

**Comment by cellocgw** [comment]
Whether or not modern keyboards have a arrow-char key,  you missed an important point:  R supports both  "<-"   and "->"  , each of which explicitly identifies the replacement source and receiver.  The use of "="  is (in my opinion as a mathematician) a BAD THING TO USE(TM) when replacing one thing with another, since that's not what the equals sign really means.  Further, in R as in all other languages which use a raw "="  ( don't forget all those  ":=" languages), the equal sign is implicitly acting from right to left.  Which is fine for Hebrew  :-)  code, I suppose.

**Comment by Ironholds** [comment]
Sure; I wrote the why not the ongoing justification.

On Tuesday, 29 March 2016, Carl Witthoft notifications@github.com wrote:

> Whether or not modern keyboards have a arrow-char key, you missed an
> important point: R supports both "<-" and "->" , each of which explicitly
> identifies the replacement source and receiver. The use of "=" is (in my
> opinion as a mathematician) a BAD THING TO USE(TM) when replacing one thing
> with another, since that's not what the equals sign really means. Further,
> in R as in all other languages which use a raw "=" ( don't forget all those
> ":=" languages), the equal sign is implicitly acting from right to left.
> Which is fine for Hebrew :-) code, I suppose.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Ironholds/rbitrary/issues/14#issuecomment-203031314

## 

Sent from my mobile computing device of Lovecraftian complexity and horror.
