### ISSUE TITLE
"good reason" to not export

### ISSUE THREAD

**Issue by dchudz** [Ironholds/rbitrary#2]
> there’s usually a good reason for something to not be exported such as, say, it’s compiled code that requires a load of R-side error checking before it’s called, and you’re about to unintentionally segfault your machine.

I would think that "because users don't need it" is a good enough reason to not export something. This seems to suggest I need a better reason.

**Comment by Ironholds** [comment]
Well, that's very deliberately an example (and one example at that). The "what to do if you need it anyway" bit implies that an absence of use cases is a common reason for things not to be exported. Do you have a suggestion for a better framing?

**Comment by dchudz** [comment]
Fair enough! I'll close.

Btw, as an alternative to 

>  emailing the author/opening a GitHub issue/delete as applicable to see if it can be exported.

... I might suggest copying the code and adding a comment crediting where it came from (if this approach is feasible). Often package authors will not want to export more than they need to, taking the attitude that even if one or a few people want to use something, that ties them to a particular implementation more than they want and they'd rather be more free to change the internals.

**Comment by Ironholds** [comment]
Ooh, that's a good idea; thanks! (I'll reopen so I don't forget, and credit you accordingly :))
