### ISSUE TITLE
library isn't all packages on your system

### ISSUE THREAD

**Issue by dchudz** [Ironholds/rbitrary#3]
>  a library is “the R packages you have on your system”.

You just want to get some more shouty emails about libraries, don't you? Anyway, as Hadley Wickham (who writes useful books and, as far as I know, no shouty emails) [wrote](http://r-pkgs.had.co.nz/package.html#library):

> A library is simply a directory containing installed packages. You can have multiple libraries on your computer. In fact, almost every one has at least two: one for packages you’ve installed, and one for the packages that come with every R installation (like base, stats, etc).

**Comment by Ironholds** [comment]
Indeed, it's a simplification, but I didn't particularly want to go into "...and sometimes you have a user-specific one as well and..."

**Comment by dchudz** [comment]
Ok! I'll close.
